### ISSUE TITLE
How to run run_experiments.sh ?

### ISSUE THREAD

**Issue by Jorigorn** [UKPLab/starsem2018-entity-linking#3]
What is parameter? 
GPUID=$1
Thanks. :)

**Comment by daniilsorokin** [comment]
That is the id of the GPU to use. If you don't have a GPU set it to any number.

**Comment by Jorigorn** [comment]
Hi, @daniilsorokin  Thanks for your reply. :)
I have GPUs, but errors show. It seem there are some other resource needed to be download?
like "data/WebQSP/preprocessed/webqsp.train.entities.candidates.4.small.pkl"
Thanks.


%  % sh ./run_experiments.sh 4
Seed: 1
Load candidates.
Traceback (most recent call last):
  File "/home/john/anaconda3/envs/starsem2018/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/john/anaconda3/envs/starsem2018/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/hdd/experiments/john/starsem2018-entity-linking/entitylinking/mlearning/training/train_entity_linker.py", line 140, in <module>
    train()
  File "/home/john/anaconda3/envs/starsem2018/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/john/anaconda3/envs/starsem2018/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/john/anaconda3/envs/starsem2018/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/john/anaconda3/envs/starsem2018/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/mnt/hdd/experiments/john/starsem2018-entity-linking/entitylinking/mlearning/training/train_entity_linker.py", line 29, in train
    precomputed_candidates = load_candidates(linking_config['linker.options']['precomputed_candidates'])
  File "/mnt/hdd/experiments/john/starsem2018-entity-linking/entitylinking/core/sentence.py", line 53, in load_candidates
    with open(precomputed_candidates_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/WebQSP/preprocessed/webqsp.train.entities.candidates.4.small.pkl'
Usage: evaluate.py [OPTIONS] PATH_TO_MODEL CONFIG_FILE_PATH

Error: Missing argumnt "config_file_path".
Usage: evaluate.py [OPTIONS] PATH_TO_MODEL CONFIG_FILE_PATH

Error: Missing argument "config_file_path".
john@serv-re ~/experiments/starsem2018-entity-linking

**Comment by daniilsorokin** [comment]
Hi,

long time waiting, but we have finally published all the evaluation data and the precomputed candidates for the evaluation: https://github.com/UKPLab/starsem2018-entity-linking#qa-data-for-benchmarking-entity-linking-systems

Best,
Daniil

**Comment by abmitra84** [comment]
Hi @daniilsorokin ,
I tried to run the run_experiments.sh ... it gets an error as `dataset.py` looking for `webqsp.dev.ids.json` in the `WebQSP/input/` directory . How to resolve this? In the preprocessed QA dataset such json files are not present.

**Comment by daniilsorokin** [comment]
Hi, 

you are right,  `webqsp.dev.ids.json` was missing from the data set and it is needed for training and evaluation using the development set. I have updated the data set online: https://public.ukp.informatik.tu-darmstadt.de/starsem18-entity-linking/EntityLinkingForQADatasets.zip

Please download again.

Cheers,
Daniil

**Comment by zou-longkun** [comment]
I trie to run the run_experiments.sh , it get an error NO such file 
 or directory "data/WebQSP/input/webqsp.train.ids.json". How to resolve this issue?

**Comment by daniilsorokin** [comment]
Hi,

the file was indeed missing, I have added it to the data set: https://public.ukp.informatik.tu-darmstadt.de/starsem18-entity-linking/EntityLinkingForQADatasets.zip

Best,
Daniil
