### ISSUE TITLE
name 'remove_links' is not defined

### ISSUE THREAD

**Issue by abmitra84** [UKPLab/starsem2018-entity-linking#4]
```
File "/<dir>/<dir>/anaconda3/bin/starsem2018/entitylinking/utils.py", line 128, in get_tagged_from_server
    input_text = remove_links(input_text)
NameError: name 'remove_links' is not defined
```
even if I comment or remove that line it still throws the same error, not sure why is it happening -

```
>>> output = entitylinker.link_entities_in_raw_input("Barack Obama is a president.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<dir>/<dir>/anaconda3/bin/starsem2018/entitylinking/core/entity_linker.py", line 130, in link_entities_in_raw_input
    sentence = self.link_entities_in_sentence_obj(sentence, element_id=element_id, num_candidates=num_candidates)
  File "/<dir>/<dir>/anaconda3/bin/starsem2018/entitylinking/core/entity_linker.py", line 77, in link_entities_in_sentence_obj
    caseless=sentence_obj.input_text.islower())
  File "/<dir>/<dir>/anaconda3/bin/starsem2018/entitylinking/utils.py", line 128, in get_tagged_from_server
    ##
NameError: name 'remove_links' is not defined
```

```
>>> output = entitylinker.link_entities_in_raw_input("Barack Obama is a president.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<dir>/<dir>/anaconda3/bin/starsem2018/entitylinking/core/entity_linker.py", line 130, in link_entities_in_raw_input
    sentence = self.link_entities_in_sentence_obj(sentence, element_id=element_id, num_candidates=num_candidates)
  File "/<dir>/<dir>/anaconda3/bin/starsem2018/entitylinking/core/entity_linker.py", line 77, in link_entities_in_sentence_obj
    caseless=sentence_obj.input_text.islower())
  File "/<dir>/<dir>/anaconda3/bin/starsem2018/entitylinking/utils.py", line 128, in get_tagged_from_server
    ##input_text = remove_links(input_text)
NameError: name 'remove_links' is not defined
```

@daniilsorokin can you suggest please? Appreciate it

**Comment by daniilsorokin** [comment]
Have you reloaded the module after commenting out the line? 

I will upload a new version, but this line is basically just removed there.

**Comment by abmitra84** [comment]
Yeah.. I removed it now. Will update this thread on how it goes. Much Appreciate your response.

**Comment by abmitra84** [comment]
We can close this issue as commenting out the `remove_links` functioned solved it
